ignoreFiles:
  - node_modules
  - app_modules
  - ui/vendor/**
  - site/assets/styles/_vendor/**

# Default rules based on
# https://github.com/salesforce-ux/stylelint-config-slds
extends: "stylelint-config-slds"

# Overrides
rules:
  "selector-class-pattern":
    - "^(nds|site|demo)(-[a-z0-9_-]+|)$"
    -
      severity: warning
      resolveNestedSelectors: true
